site_name: OpenPAI Handbook
repo_url: https://github.com/mydmdm/openpai-handbook
theme: readthedocs
use_directory_urls: false
nav:
  - Overview: index.md
  - User Manual: manual/cluster-user/README.md
  - Cluster Admin Manual: manual/cluster-admin/README.md
